export enum Role {
  PATIENT = 'PATIENT',
  DOCTOR = 'DOCTOR',
  PHARMACY = 'PHARMACY',
  CLINIC = 'CLINIC',
  ADMIN = 'ADMIN',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum StockStatus {
  IN_STOCK = 'IN_STOCK',
  LOW_STOCK = 'LOW_STOCK',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  UNVERIFIED = 'UNVERIFIED',
}

export enum AppointmentType {
  IN_PERSON = 'IN_PERSON',
  TELECONSULTATION = 'TELECONSULTATION',
  HOME_VISIT = 'HOME_VISIT',
}

export enum AppointmentStatus {
  REQUESTED = 'REQUESTED',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
}

export enum ReservationStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  READY = 'READY',
  COLLECTED = 'COLLECTED',
  CANCELLED = 'CANCELLED',
}

export enum PlanType {
  FREE = 'FREE',
  DOCTOR_BASIC = 'DOCTOR_BASIC',
  DOCTOR_PRO = 'DOCTOR_PRO',
  PHARMACY_BASIC = 'PHARMACY_BASIC',
  PHARMACY_PRO = 'PHARMACY_PRO',
  PHARMACY_PREMIUM = 'PHARMACY_PREMIUM',
  CLINIC_STANDARD = 'CLINIC_STANDARD',
  CLINIC_PREMIUM = 'CLINIC_PREMIUM',
  ENTERPRISE = 'ENTERPRISE',
}

export enum SubscriptionStatus {
  TRIAL = 'TRIAL',
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}
